apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfm-deploy
  labels:
    app: sfm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sfm
  template:
    metadata:
      labels:
        app: sfm
    spec:
      containers:
      - name: sfm
        image: aakashhandibar/stock_forecasting:v2.1
        ports:
        - containerPort: 8501

